### ISSUE TITLE
[REFACTOR] 이미지 객체들 엔티티에 합치기

### ISSUE THREAD

**Issue by ppirae** [YeoGiDa/YeoGiDa-Backend#156]
## 💡 Issue
- 현재 이미지 객체와 엔티티가 분리되어 있는데 합치는 코드 리팩토링을 진행한다.

## 📝 todo
- [x] member 이미지 객체와 엔티티 합치기
- [x] trip 이미지 객체와 엔티티 합치기
- [x] place 이미지 객체와 엔티티 합치기
- [x] 이상없는지 기능 테스트

**Comment by ppirae** [comment]
리팩토링 작업 진행했으나 API 명세서 변경해야해서
프론트와 협의후에 진행예정
브랜치 커밋만 하고 푸쉬 안한상태
