### ISSUE TITLE
[FEAT] 전체 여행지 검색 및 정렬 API 개발

### ISSUE THREAD

**Issue by ppirae** [YeoGiDa/YeoGiDa-Backend#160]
## 💡 Issue
- 전체 여행지 검색 및 정렬 API 개발

## 📝 todo
- [x] 전체 여행지 검색 API 개발
- [x] 전체 여행지 검색 결과에서 최신순 정렬 API
- [x] 전체 여행지 검색 결과에서 좋아요순 정렬 API
- [x] 테스트
